[package]
name = "otel-arrow-hacking"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "55.0.0"
arrow-array = "55.0.0"
arrow-schema = "55.0.0"
object_store = "0.12.0"
parquet = { version = "55.0.0", features = ["arrow", "async", "object_store"]}
tokio = { version = "1", features = ["full"] }