[package]
name = "otel-arrow-hacking"
version = "0.1.0"
edition = "2024"

[dependencies]
# local
otel-arrow-rust = { path = "../otel-arrow/rust/otel-arrow-rust" }
# external
arrow = "53"
arrow-array = "53"
arrow-ipc = {version = "53", features = ["zstd"] }
arrow-schema = "53"
iceberg = {git = "https://github.com/apache/iceberg-rust.git", tag="v0.4.0"}
iceberg-catalog-rest = {git = "https://github.com/apache/iceberg-rust.git", tag="v0.4.0"}
# iceberg-catalog-memory = "0.4.0"
iceberg-catalog-sql = {git = "https://github.com/apache/iceberg-rust.git", tag="v0.4.0"}
object_store = "0.11.0"
parquet = { version = "53.0.0", features = ["arrow", "async", "object_store"]}
prost = "~0.13"
sqlx = { version = "0.8.1", features = ["any", "sqlite", "migrate", "runtime-tokio"], default-features = false }
tokio = { version = "1", features = ["full"] }